# Python review: More exercises

This notebook continues the review of Python basics. A key concept is that of a _nested_ data structure.

In [1]:
### Global imports
import dill
from cse6040_devkit import plugins, utils
from cse6040_devkit.training_wheels import run_with_timeout, suppress_stdout
import tracemalloc
from time import time
import re 
import pandas as pd



Consider the following dataset of exam grades, organized as a 2-D table and stored in Python as a "list of lists" under the variable name, `grades`. You will use this 2-D table throughout this notebook.

In [2]:
grades = [
    # First line is descriptive header. Subsequent lines hold data
    ['Student', 'Exam 1', 'Exam 2', 'Exam 3'],
    ['Thorny', '100', '90', '80'],
    ['Mac', '88', '99', '111'],
    ['Farva', '45', '56', '67'],
    ['Rabbit', '59', '61', '67'],
    ['Ursula', '73', '79', '83'],
    ['Foster', '89', '97', '101']
]

grades

### Exercise 0: (1 points)
**get_students**  

**Your task:** define `get_students` as follows:


Write a function that returns the students names from "top to bottom".

**Inputs**:
- `grades` (list): a nested list of grades

**Return**:
- `students` (list): a list representing the list of students names as they appear from "top to bottom".


In [15]:
### Solution - Exercise 0  
def get_students(grades: list) -> list:
    ###
    ### YOUR CODE HERE
    ###
    students = []
    for row in grades[1:]:
        students.append(row[0])
    return students
            

### Demo function call
grades = [
# First line is descriptive header. Subsequent lines hold data
['Student', 'Exam 1', 'Exam 2', 'Exam 3'],
['Thorny', '100', '90', '80'],
['Mac', '88', '99', '111'],
['Farva', '45', '56', '67'],
['Rabbit', '59', '61', '67'],
['Ursula', '73', '79', '83'],
['Foster', '89', '97', '101']
]
print(f'result={get_students(grades)}')

result=['Thorny', 'Mac', 'Farva', 'Rabbit', 'Ursula', 'Foster']


 

**The demo should display this printed output.**
```
result=['Thorny', 'Mac', 'Farva', 'Rabbit', 'Ursula', 'Foster']
```


 ---
 <!-- Test Cell Boilerplate -->  
The cell below will test your solution for get_students (exercise 0). The testing variables will be available for debugging under the following names in a dictionary format.  
- `input_vars` - Input variables for your solution.   
- `original_input_vars` - Copy of input variables from prior to running your solution. Any `key:value` pair in `original_input_vars` should also exist in `input_vars` - otherwise the inputs were modified by your solution.  
- `returned_output_vars` - Outputs returned by your solution.  
- `true_output_vars` - The expected output. This _should_ "match" `returned_output_vars` based on the question requirements - otherwise, your solution is not returning the correct output. 


In [15]:
### Test Cell - Exercise 0  


from cse6040_devkit.tester_fw.testers import Tester
from yaml import safe_load
from time import time

tracemalloc.start()
mem_start, peak_start = tracemalloc.get_traced_memory()
print(f"initial memory usage: {mem_start/1024/1024:.2f} MB")

# Load testing utility
with open('resource/asnlib/publicdata/execute_tests', 'rb') as f:
    executor = dill.load(f)

@run_with_timeout(error_threshold=200.0, warning_threshold=100.0)
@suppress_stdout
def execute_tests(**kwargs):
    return executor(**kwargs)


# Execute test
start_time = time()
passed, test_case_vars, e = execute_tests(func=get_students,
              ex_name='get_students',
              key=b'8VGfIctvRdgA0ZvvNEVbMI2yu6UDz3sdBSZX59VpBSo=', 
              n_iter=50)
# Assign test case vars for debugging
input_vars, original_input_vars, returned_output_vars, true_output_vars = test_case_vars
duration = time() - start_time
print(f"Test duration: {duration:.2f} seconds")
current_memory, peak_memory = tracemalloc.get_traced_memory()
print(f"memory after test: {current_memory/1024/1024:.2f} MB")
print(f"memory peak during test: {peak_memory/1024/1024:.2f} MB")
tracemalloc.stop()
if e: raise e
assert passed, 'The solution to get_students did not pass the test.'

###
### AUTOGRADER TEST - DO NOT REMOVE
###

print('Passed! Please submit.')

initial memory usage: 0.00 MB


NameError: name 'get_students' is not defined

### Exercise 1: (1 points)
**get_assignments**  

**Your task:** define `get_assignments` as follows:


Write a function that returns the assignment names.

**Inputs**:
- `grades` (list): a nested list of grades

**Return**:
- `assignments` (list): a list representing the assignment names.


In [12]:
### Solution - Exercise 1  
def get_assignments(grades: list) -> list:
    ###
    ### YOUR CODE HERE
    ###
    assignments = []
    for row in grades[0][1:]:
        assignments.append(row)
    return assignments
    
### Demo function call
grades = [
# First line is descriptive header. Subsequent lines hold data
['Student', 'Exam 1', 'Exam 2', 'Exam 3'],
['Thorny', '100', '90', '80'],
['Mac', '88', '99', '111'],
['Farva', '45', '56', '67'],
['Rabbit', '59', '61', '67'],
['Ursula', '73', '79', '83'],
['Foster', '89', '97', '101']
]
print(f'result={get_assignments(grades)}')

result=['Exam 1', 'Exam 2', 'Exam 3']


 

**The demo should display this printed output.**
```
result=['Exam 1', 'Exam 2', 'Exam 3']
```


 ---
 <!-- Test Cell Boilerplate -->  
The cell below will test your solution for get_assignments (exercise 1). The testing variables will be available for debugging under the following names in a dictionary format.  
- `input_vars` - Input variables for your solution.   
- `original_input_vars` - Copy of input variables from prior to running your solution. Any `key:value` pair in `original_input_vars` should also exist in `input_vars` - otherwise the inputs were modified by your solution.  
- `returned_output_vars` - Outputs returned by your solution.  
- `true_output_vars` - The expected output. This _should_ "match" `returned_output_vars` based on the question requirements - otherwise, your solution is not returning the correct output. 


In [16]:
### Test Cell - Exercise 1  


from cse6040_devkit.tester_fw.testers import Tester
from yaml import safe_load
from time import time

tracemalloc.start()
mem_start, peak_start = tracemalloc.get_traced_memory()
print(f"initial memory usage: {mem_start/1024/1024:.2f} MB")

# Load testing utility
with open('resource/asnlib/publicdata/execute_tests', 'rb') as f:
    executor = dill.load(f)

@run_with_timeout(error_threshold=200.0, warning_threshold=100.0)
@suppress_stdout
def execute_tests(**kwargs):
    return executor(**kwargs)


# Execute test
start_time = time()
passed, test_case_vars, e = execute_tests(func=get_assignments,
              ex_name='get_assignments',
              key=b'8VGfIctvRdgA0ZvvNEVbMI2yu6UDz3sdBSZX59VpBSo=', 
              n_iter=50)
# Assign test case vars for debugging
input_vars, original_input_vars, returned_output_vars, true_output_vars = test_case_vars
duration = time() - start_time
print(f"Test duration: {duration:.2f} seconds")
current_memory, peak_memory = tracemalloc.get_traced_memory()
print(f"memory after test: {current_memory/1024/1024:.2f} MB")
print(f"memory peak during test: {peak_memory/1024/1024:.2f} MB")
tracemalloc.stop()
if e: raise e
assert passed, 'The solution to get_assignments did not pass the test.'

###
### AUTOGRADER TEST - DO NOT REMOVE
###

print('Passed! Please submit.')

initial memory usage: 0.12 MB
Test duration: 0.14 seconds
memory after test: 3.23 MB
memory peak during test: 4.56 MB
Passed! Please submit.


### Exercise 2: (1 points)
**build_grade_lists**  

**Your task:** define `build_grade_lists` as follows:


Write a function that returns a dictionary of scores for each student.

**Inputs**:
- `grades` (list): a nested list of grades

**Return**:
- `grade_lists` (dict): 
  - key is a student
  - value is a list of scores with the scores converted to integers


In [6]:
### Solution - Exercise 2  
def build_grade_lists(grades: list) -> dict:
    ###
    ### YOUR CODE HERE
    ###
    names = []
    grade = []
    for row in grades[1:]:
        names.append(row[0])
        grade.append(row[1:])
  
    grade_int = []
    for sublist in grade:
        student_grade = []
        for str in sublist:
            student_grade.append(int(str))
            
        grade_int.append(student_grade)
            
    grade_lists = dict(zip(names, grade_int))
    return grade_lists

    
### Demo function call
grades = [
# First line is descriptive header. Subsequent lines hold data
['Student', 'Exam 1', 'Exam 2', 'Exam 3'],
['Thorny', '100', '90', '80'],
['Mac', '88', '99', '111'],
['Farva', '45', '56', '67'],
['Rabbit', '59', '61', '67'],
['Ursula', '73', '79', '83'],
['Foster', '89', '97', '101']
]
print(f'result={build_grade_lists(grades)}')

result={'Thorny': [100, 90, 80], 'Mac': [88, 99, 111], 'Farva': [45, 56, 67], 'Rabbit': [59, 61, 67], 'Ursula': [73, 79, 83], 'Foster': [89, 97, 101]}


 

**The demo should display this printed output.**
```
result={'Thorny': [100, 90, 80], 'Mac': [88, 99, 111], 'Farva': [45, 56, 67], 'Rabbit': [59, 61, 67], 'Ursula': [73, 79, 83], 'Foster': [89, 97, 101]}
```


 ---
 <!-- Test Cell Boilerplate -->  
The cell below will test your solution for build_grade_lists (exercise 2). The testing variables will be available for debugging under the following names in a dictionary format.  
- `input_vars` - Input variables for your solution.   
- `original_input_vars` - Copy of input variables from prior to running your solution. Any `key:value` pair in `original_input_vars` should also exist in `input_vars` - otherwise the inputs were modified by your solution.  
- `returned_output_vars` - Outputs returned by your solution.  
- `true_output_vars` - The expected output. This _should_ "match" `returned_output_vars` based on the question requirements - otherwise, your solution is not returning the correct output. 


In [7]:
### Test Cell - Exercise 2  


from cse6040_devkit.tester_fw.testers import Tester
from yaml import safe_load
from time import time

tracemalloc.start()
mem_start, peak_start = tracemalloc.get_traced_memory()
print(f"initial memory usage: {mem_start/1024/1024:.2f} MB")

# Load testing utility
with open('resource/asnlib/publicdata/execute_tests', 'rb') as f:
    executor = dill.load(f)

@run_with_timeout(error_threshold=200.0, warning_threshold=100.0)
@suppress_stdout
def execute_tests(**kwargs):
    return executor(**kwargs)


# Execute test
start_time = time()
passed, test_case_vars, e = execute_tests(func=build_grade_lists,
              ex_name='build_grade_lists',
              key=b'8VGfIctvRdgA0ZvvNEVbMI2yu6UDz3sdBSZX59VpBSo=', 
              n_iter=50)
# Assign test case vars for debugging
input_vars, original_input_vars, returned_output_vars, true_output_vars = test_case_vars
duration = time() - start_time
print(f"Test duration: {duration:.2f} seconds")
current_memory, peak_memory = tracemalloc.get_traced_memory()
print(f"memory after test: {current_memory/1024/1024:.2f} MB")
print(f"memory peak during test: {peak_memory/1024/1024:.2f} MB")
tracemalloc.stop()
if e: raise e
assert passed, 'The solution to build_grade_lists did not pass the test.'

###
### AUTOGRADER TEST - DO NOT REMOVE
###

print('Passed! Please submit.')

initial memory usage: 0.00 MB
Test duration: 0.15 seconds
memory after test: 0.05 MB
memory peak during test: 1.43 MB
Passed! Please submit.


### Exercise 3: (2 points)
**build_grade_dicts**  

**Your task:** define `build_grade_dicts` as follows:


Write a function that returns a dictionary of scores for each student.

**Inputs**:
- `grades` (list): a nested list of grades

**Return**:
- `grade_dicts` (dict): a nested dictionary 
  - key is a student
  - value is another dictionary
    - key is the assignment
    - value is the score as an integer

**Hint**: 
- You may find earlier exercises useful for completing this exercise.


In [14]:
### Solution - Exercise 3  
def build_grade_dicts(grades: list) -> dict:
    ###
    ### YOUR CODE HERE
    ###
    
    grade_dicts = {}
    exams = grades[0][1:]
   
    
    for row in grades[1:]:
        names = row[0]
        score = row[1:]
        
        score_int = []
        for s in score:
            score_int.append(int(s))
            
        exam_score = dict(zip(exams, score_int))
        grade_dicts[names] = exam_score
    
    
    return grade_dicts

### Demo function call
grades = [
# First line is descriptive header. Subsequent lines hold data
['Student', 'Exam 1', 'Exam 2', 'Exam 3'],
['Thorny', '100', '90', '80'],
['Mac', '88', '99', '111'],
['Farva', '45', '56', '67'],
['Rabbit', '59', '61', '67'],
['Ursula', '73', '79', '83'],
['Foster', '89', '97', '101']
]
print(f'result={build_grade_dicts(grades)}')

result={'Thorny': {'Exam 1': 100, 'Exam 2': 90, 'Exam 3': 80}, 'Mac': {'Exam 1': 88, 'Exam 2': 99, 'Exam 3': 111}, 'Farva': {'Exam 1': 45, 'Exam 2': 56, 'Exam 3': 67}, 'Rabbit': {'Exam 1': 59, 'Exam 2': 61, 'Exam 3': 67}, 'Ursula': {'Exam 1': 73, 'Exam 2': 79, 'Exam 3': 83}, 'Foster': {'Exam 1': 89, 'Exam 2': 97, 'Exam 3': 101}}


 

**The demo should display this printed output.**
```
result={'Thorny': {'Exam 1': 100, 'Exam 2': 90, 'Exam 3': 80}, 'Mac': {'Exam 1': 88, 'Exam 2': 99, 'Exam 3': 111}, 'Farva': {'Exam 1': 45, 'Exam 2': 56, 'Exam 3': 67}, 'Rabbit': {'Exam 1': 59, 'Exam 2': 61, 'Exam 3': 67}, 'Ursula': {'Exam 1': 73, 'Exam 2': 79, 'Exam 3': 83}, 'Foster': {'Exam 1': 89, 'Exam 2': 97, 'Exam 3': 101}}
```


 ---
 <!-- Test Cell Boilerplate -->  
The cell below will test your solution for build_grade_dicts (exercise 3). The testing variables will be available for debugging under the following names in a dictionary format.  
- `input_vars` - Input variables for your solution.   
- `original_input_vars` - Copy of input variables from prior to running your solution. Any `key:value` pair in `original_input_vars` should also exist in `input_vars` - otherwise the inputs were modified by your solution.  
- `returned_output_vars` - Outputs returned by your solution.  
- `true_output_vars` - The expected output. This _should_ "match" `returned_output_vars` based on the question requirements - otherwise, your solution is not returning the correct output. 


In [15]:
### Test Cell - Exercise 3  


from cse6040_devkit.tester_fw.testers import Tester
from yaml import safe_load
from time import time

tracemalloc.start()
mem_start, peak_start = tracemalloc.get_traced_memory()
print(f"initial memory usage: {mem_start/1024/1024:.2f} MB")

# Load testing utility
with open('resource/asnlib/publicdata/execute_tests', 'rb') as f:
    executor = dill.load(f)

@run_with_timeout(error_threshold=200.0, warning_threshold=100.0)
@suppress_stdout
def execute_tests(**kwargs):
    return executor(**kwargs)


# Execute test
start_time = time()
passed, test_case_vars, e = execute_tests(func=build_grade_dicts,
              ex_name='build_grade_dicts',
              key=b'8VGfIctvRdgA0ZvvNEVbMI2yu6UDz3sdBSZX59VpBSo=', 
              n_iter=50)
# Assign test case vars for debugging
input_vars, original_input_vars, returned_output_vars, true_output_vars = test_case_vars
duration = time() - start_time
print(f"Test duration: {duration:.2f} seconds")
current_memory, peak_memory = tracemalloc.get_traced_memory()
print(f"memory after test: {current_memory/1024/1024:.2f} MB")
print(f"memory peak during test: {peak_memory/1024/1024:.2f} MB")
tracemalloc.stop()
if e: raise e
assert passed, 'The solution to build_grade_dicts did not pass the test.'

###
### AUTOGRADER TEST - DO NOT REMOVE
###

print('Passed! Please submit.')

initial memory usage: 0.00 MB
Test duration: 0.24 seconds
memory after test: 3.16 MB
memory peak during test: 4.57 MB
Passed! Please submit.


### Exercise 4: (1 points)
**build_avg_by_student**  

**Your task:** define `build_avg_by_student` as follows:


Write a function that returns a dictionary of average scores for each student.

**Inputs**:
- `grades` (list): a nested list of grades

**Return**:
- `avg_grades` (dict): a dictionary 
  - key is a student
  - value is an average grade for that student rounded to 3 decimal places

**Hint**: 
- You may find earlier exercises useful for completing this exercise.
- The [statistics](https://docs.python.org/3.5/library/statistics.html) module has at least one helpful function.
- The [round](https://docs.python.org/3/library/functions.html#round) function will be helpful.


In [19]:
### Solution - Exercise 4  
def build_avg_by_student(grades: list) -> dict:
    ###
    ### YOUR CODE HERE
    ###
    avg_grades = {}
    for row in grades[1:]:
        student_names = row[0]
        scores = row[1:]
        scores_int = []
        for s in scores:
            scores_int.append(int(s))
        score_ave = round(sum(scores_int) / len(scores_int),3) 
    
        avg_grades[student_names] = score_ave
    
    return avg_grades

### Demo function call
grades = [
# First line is descriptive header. Subsequent lines hold data
['Student', 'Exam 1', 'Exam 2', 'Exam 3'],
['Thorny', '100', '90', '80'],
['Mac', '88', '99', '111'],
['Farva', '45', '56', '67'],
['Rabbit', '59', '61', '67'],
['Ursula', '73', '79', '83'],
['Foster', '89', '97', '101']
]
print(f'result={build_avg_by_student(grades)}')

result={'Thorny': 90.0, 'Mac': 99.333, 'Farva': 56.0, 'Rabbit': 62.333, 'Ursula': 78.333, 'Foster': 95.667}


 

**The demo should display this printed output.**
```
result={'Thorny': 90, 'Mac': 99.333, 'Farva': 56, 'Rabbit': 62.333, 'Ursula': 78.333, 'Foster': 95.667}
```


 ---
 <!-- Test Cell Boilerplate -->  
The cell below will test your solution for build_avg_by_student (exercise 4). The testing variables will be available for debugging under the following names in a dictionary format.  
- `input_vars` - Input variables for your solution.   
- `original_input_vars` - Copy of input variables from prior to running your solution. Any `key:value` pair in `original_input_vars` should also exist in `input_vars` - otherwise the inputs were modified by your solution.  
- `returned_output_vars` - Outputs returned by your solution.  
- `true_output_vars` - The expected output. This _should_ "match" `returned_output_vars` based on the question requirements - otherwise, your solution is not returning the correct output. 


In [20]:
### Test Cell - Exercise 4  


from cse6040_devkit.tester_fw.testers import Tester
from yaml import safe_load
from time import time

tracemalloc.start()
mem_start, peak_start = tracemalloc.get_traced_memory()
print(f"initial memory usage: {mem_start/1024/1024:.2f} MB")

# Load testing utility
with open('resource/asnlib/publicdata/execute_tests', 'rb') as f:
    executor = dill.load(f)

@run_with_timeout(error_threshold=200.0, warning_threshold=100.0)
@suppress_stdout
def execute_tests(**kwargs):
    return executor(**kwargs)


# Execute test
start_time = time()
passed, test_case_vars, e = execute_tests(func=build_avg_by_student,
              ex_name='build_avg_by_student',
              key=b'8VGfIctvRdgA0ZvvNEVbMI2yu6UDz3sdBSZX59VpBSo=', 
              n_iter=50)
# Assign test case vars for debugging
input_vars, original_input_vars, returned_output_vars, true_output_vars = test_case_vars
duration = time() - start_time
print(f"Test duration: {duration:.2f} seconds")
current_memory, peak_memory = tracemalloc.get_traced_memory()
print(f"memory after test: {current_memory/1024/1024:.2f} MB")
print(f"memory peak during test: {peak_memory/1024/1024:.2f} MB")
tracemalloc.stop()
if e: raise e
assert passed, 'The solution to build_avg_by_student did not pass the test.'

###
### AUTOGRADER TEST - DO NOT REMOVE
###

print('Passed! Please submit.')

initial memory usage: 0.00 MB
Test duration: 0.09 seconds
memory after test: 0.04 MB
memory peak during test: 1.46 MB
Passed! Please submit.


### Exercise 5: (2 points)
**build_grade_by_asn**  

**Your task:** define `build_grade_by_asn` as follows:


Write a function that returns a dictionary of scores for each assignment.

**Inputs**:
- `grades` (list): a nested list of grades

**Return**:
- `grades_by_assignment` (dict): a dictionary 
  - key is an assignment
  - value is a list of scores with the scores converted to integers

**Hint**: 
- You may find earlier exercises useful for completing this exercise.


In [2]:
### Solution - Exercise 5  
def build_grade_by_asn(grades: list) -> dict:
    ###
    ### YOUR CODE HERE
    ###
    grades_by_assignment = {}
    
    exams = grades[0][1:]
    for exam in exams:
        grades_by_assignment[exam] =[]
        

    for row in grades[1:]:
        scores = row[1:]
       
        for i in range(len(exams)):
            exam_name = exams[i]
            score_int = int(scores[i])
            grades_by_assignment[exam_name].append(score_int)         
                       
                               
    return grades_by_assignment
            
        
### Demo function call
grades = [
# First line is descriptive header. Subsequent lines hold data
['Student', 'Exam 1', 'Exam 2', 'Exam 3'],
['Thorny', '100', '90', '80'],
['Mac', '88', '99', '111'],
['Farva', '45', '56', '67'],
['Rabbit', '59', '61', '67'],
['Ursula', '73', '79', '83'],
['Foster', '89', '97', '101']
]
print(f'result={build_grade_by_asn(grades)}')

result={'Exam 1': [100, 88, 45, 59, 73, 89], 'Exam 2': [90, 99, 56, 61, 79, 97], 'Exam 3': [80, 111, 67, 67, 83, 101]}


 

**The demo should display this printed output.**
```
result={'Exam 1': [100, 88, 45, 59, 73, 89], 'Exam 2': [90, 99, 56, 61, 79, 97], 'Exam 3': [80, 111, 67, 67, 83, 101]}
```


 ---
 <!-- Test Cell Boilerplate -->  
The cell below will test your solution for build_grade_by_asn (exercise 5). The testing variables will be available for debugging under the following names in a dictionary format.  
- `input_vars` - Input variables for your solution.   
- `original_input_vars` - Copy of input variables from prior to running your solution. Any `key:value` pair in `original_input_vars` should also exist in `input_vars` - otherwise the inputs were modified by your solution.  
- `returned_output_vars` - Outputs returned by your solution.  
- `true_output_vars` - The expected output. This _should_ "match" `returned_output_vars` based on the question requirements - otherwise, your solution is not returning the correct output. 


In [3]:
### Test Cell - Exercise 5  


from cse6040_devkit.tester_fw.testers import Tester
from yaml import safe_load
from time import time

tracemalloc.start()
mem_start, peak_start = tracemalloc.get_traced_memory()
print(f"initial memory usage: {mem_start/1024/1024:.2f} MB")

# Load testing utility
with open('resource/asnlib/publicdata/execute_tests', 'rb') as f:
    executor = dill.load(f)

@run_with_timeout(error_threshold=200.0, warning_threshold=100.0)
@suppress_stdout
def execute_tests(**kwargs):
    return executor(**kwargs)


# Execute test
start_time = time()
passed, test_case_vars, e = execute_tests(func=build_grade_by_asn,
              ex_name='build_grade_by_asn',
              key=b'8VGfIctvRdgA0ZvvNEVbMI2yu6UDz3sdBSZX59VpBSo=', 
              n_iter=50)
# Assign test case vars for debugging
input_vars, original_input_vars, returned_output_vars, true_output_vars = test_case_vars
duration = time() - start_time
print(f"Test duration: {duration:.2f} seconds")
current_memory, peak_memory = tracemalloc.get_traced_memory()
print(f"memory after test: {current_memory/1024/1024:.2f} MB")
print(f"memory peak during test: {peak_memory/1024/1024:.2f} MB")
tracemalloc.stop()
if e: raise e
assert passed, 'The solution to build_grade_by_asn did not pass the test.'

###
### AUTOGRADER TEST - DO NOT REMOVE
###

print('Passed! Please submit.')

initial memory usage: 0.00 MB
Test duration: 0.28 seconds
memory after test: 3.18 MB
memory peak during test: 4.59 MB
Passed! Please submit.


### Exercise 6: (1 points)
**build_avg_by_asn**  

**Your task:** define `build_avg_by_asn` as follows:


Write a function that returns a dictionary of average scores for each assignment.

**Inputs**:
- `grades` (list): a nested list of grades

**Return**:
- `avg_assignment` (dict): a dictionary 
  - key is an assignment
  - value is an average grade for that assignment rounded to 3 decimal places

**Hint**: 
- You may find earlier exercises useful for completing this exercise.
- The [statistics](https://docs.python.org/3.5/library/statistics.html) module has at least one helpful function.
- The [round](https://docs.python.org/3/library/functions.html#round) function will be helpful.


In [9]:
### Solution - Exercise 6  
def build_avg_by_asn(grades: list) -> dict:
    ###
    ### YOUR CODE HERE
    ###
    avg_assignment = {}
   
    exams = grades[0][1:]
    for exam in exams:
        avg_assignment[exam] = []
    
    for row in grades[1:]:
        scores = row[1:]
        
        for i in range(len(exams)):
            exam_name = exams[i]
            score = int(scores[i])
            avg_assignment[exam_name].append(score)
            
    for exam_name in exams:
        all_scores = avg_assignment[exam_name]
        av_score = round(sum(all_scores) / len(all_scores), 3)
        avg_assignment[exam_name] = av_score
        
        
                        
    return avg_assignment
        

### Demo function call
grades = [
# First line is descriptive header. Subsequent lines hold data
['Student', 'Exam 1', 'Exam 2', 'Exam 3'],
['Thorny', '100', '90', '80'],
['Mac', '88', '99', '111'],
['Farva', '45', '56', '67'],
['Rabbit', '59', '61', '67'],
['Ursula', '73', '79', '83'],
['Foster', '89', '97', '101']
]
print(f'result={build_avg_by_asn(grades)}')

result={'Exam 1': 75.667, 'Exam 2': 80.333, 'Exam 3': 84.833}


 

**The demo should display this printed output.**
```
result={'Exam 1': 75.667, 'Exam 2': 80.333, 'Exam 3': 84.833}
```


 ---
 <!-- Test Cell Boilerplate -->  
The cell below will test your solution for build_avg_by_asn (exercise 6). The testing variables will be available for debugging under the following names in a dictionary format.  
- `input_vars` - Input variables for your solution.   
- `original_input_vars` - Copy of input variables from prior to running your solution. Any `key:value` pair in `original_input_vars` should also exist in `input_vars` - otherwise the inputs were modified by your solution.  
- `returned_output_vars` - Outputs returned by your solution.  
- `true_output_vars` - The expected output. This _should_ "match" `returned_output_vars` based on the question requirements - otherwise, your solution is not returning the correct output. 


In [10]:
### Test Cell - Exercise 6  


from cse6040_devkit.tester_fw.testers import Tester
from yaml import safe_load
from time import time

tracemalloc.start()
mem_start, peak_start = tracemalloc.get_traced_memory()
print(f"initial memory usage: {mem_start/1024/1024:.2f} MB")

# Load testing utility
with open('resource/asnlib/publicdata/execute_tests', 'rb') as f:
    executor = dill.load(f)

@run_with_timeout(error_threshold=200.0, warning_threshold=100.0)
@suppress_stdout
def execute_tests(**kwargs):
    return executor(**kwargs)


# Execute test
start_time = time()
passed, test_case_vars, e = execute_tests(func=build_avg_by_asn,
              ex_name='build_avg_by_asn',
              key=b'8VGfIctvRdgA0ZvvNEVbMI2yu6UDz3sdBSZX59VpBSo=', 
              n_iter=50)
# Assign test case vars for debugging
input_vars, original_input_vars, returned_output_vars, true_output_vars = test_case_vars
duration = time() - start_time
print(f"Test duration: {duration:.2f} seconds")
current_memory, peak_memory = tracemalloc.get_traced_memory()
print(f"memory after test: {current_memory/1024/1024:.2f} MB")
print(f"memory peak during test: {peak_memory/1024/1024:.2f} MB")
tracemalloc.stop()
if e: raise e
assert passed, 'The solution to build_avg_by_asn did not pass the test.'

###
### AUTOGRADER TEST - DO NOT REMOVE
###

print('Passed! Please submit.')

initial memory usage: 0.00 MB
Test duration: 0.08 seconds
memory after test: 0.03 MB
memory peak during test: 1.43 MB
Passed! Please submit.


### Exercise 7: (2 points)
**get_ranked_students**  

**Your task:** define `get_ranked_students` as follows:


Write a function that returns a list of sorted students.

**Inputs**:
- `grades` (list): a nested list of grades

**Return**:
- `ranked_students` (list): a list containing students ordered by: 
  - average score descending order
  - break any ties by name in ascending alphabetical order 

**Hint**: 
- You may find earlier exercises useful for completing this exercise.
- `ranked_students[0]` would be the student with the highest average exam score while `ranked_students[-1]` would have the lowest average exam score.


In [24]:
### Solution - Exercise 7  
def get_ranked_students(grades: list) -> list:
    ###
    ### YOUR CODE HERE
    ###
    ranked_students = []
    avg_grades = {}
    for row in grades[1:]:
        student_names = row[0]
        scores = row[1:]
        scores_int = []
        for s in scores:
            scores_int.append(int(s))
        score_ave = round(sum(scores_int) / len(scores_int),3) 
    
        avg_grades[student_names] = score_ave
        
     #convert  avg_grades dict to a list
    student_list = list(avg_grades.items())
    #sort the list 
    student_list.sort(key=lambda x: (-x[1], x[0]))
    
    for student in student_list:
         ranked_students.append(student[0])

    
    return ranked_students
    

### Demo function call
grades = [
# First line is descriptive header. Subsequent lines hold data
['Student', 'Exam 1', 'Exam 2', 'Exam 3'],
['Thorny', '100', '90', '80'],
['Mac', '88', '99', '111'],
['Farva', '45', '56', '67'],
['Rabbit', '59', '61', '67'],
['Ursula', '73', '79', '83'],
['Foster', '89', '97', '101'],
['Abigail', '99', '99', '100']
]
print(f'result={get_ranked_students(grades)}')

result=['Abigail', 'Mac', 'Foster', 'Thorny', 'Ursula', 'Rabbit', 'Farva']


 

**The demo should display this printed output.**
```
result=['Abigail', 'Mac', 'Foster', 'Thorny', 'Ursula', 'Rabbit', 'Farva']
```


 ---
 <!-- Test Cell Boilerplate -->  
The cell below will test your solution for get_ranked_students (exercise 7). The testing variables will be available for debugging under the following names in a dictionary format.  
- `input_vars` - Input variables for your solution.   
- `original_input_vars` - Copy of input variables from prior to running your solution. Any `key:value` pair in `original_input_vars` should also exist in `input_vars` - otherwise the inputs were modified by your solution.  
- `returned_output_vars` - Outputs returned by your solution.  
- `true_output_vars` - The expected output. This _should_ "match" `returned_output_vars` based on the question requirements - otherwise, your solution is not returning the correct output. 


In [25]:
### Test Cell - Exercise 7  


from cse6040_devkit.tester_fw.testers import Tester
from yaml import safe_load
from time import time

tracemalloc.start()
mem_start, peak_start = tracemalloc.get_traced_memory()
print(f"initial memory usage: {mem_start/1024/1024:.2f} MB")

# Load testing utility
with open('resource/asnlib/publicdata/execute_tests', 'rb') as f:
    executor = dill.load(f)

@run_with_timeout(error_threshold=200.0, warning_threshold=100.0)
@suppress_stdout
def execute_tests(**kwargs):
    return executor(**kwargs)


# Execute test
start_time = time()
passed, test_case_vars, e = execute_tests(func=get_ranked_students,
              ex_name='get_ranked_students',
              key=b'8VGfIctvRdgA0ZvvNEVbMI2yu6UDz3sdBSZX59VpBSo=', 
              n_iter=50)
# Assign test case vars for debugging
input_vars, original_input_vars, returned_output_vars, true_output_vars = test_case_vars
duration = time() - start_time
print(f"Test duration: {duration:.2f} seconds")
current_memory, peak_memory = tracemalloc.get_traced_memory()
print(f"memory after test: {current_memory/1024/1024:.2f} MB")
print(f"memory peak during test: {peak_memory/1024/1024:.2f} MB")
tracemalloc.stop()
if e: raise e
assert passed, 'The solution to get_ranked_students did not pass the test.'

###
### AUTOGRADER TEST - DO NOT REMOVE
###

print('Passed! Please submit.')

initial memory usage: 0.00 MB
Test duration: 0.06 seconds
memory after test: 0.03 MB
memory peak during test: 1.45 MB
Passed! Please submit.


### FIN!
You've reached the end of this part. Don't forget to restart and run all cells again to make sure it's all working when run in sequence; and make sure your work passes the submission process. Good luck!